apiVersion: v1
kind: Pod
metadata:
     name: mypod1
     labels:
         env: development
         class: pods
         love: devops
spec:
   containers:
   - name: coo1
     image: ubuntu
     command: ["bin/bash" , "-c" , "while true; do echo Hi Mohini ; sleep 5 ; done"]
