apiVersion: v1
kind: Pod
metadata:
        name: nodelabels
        labels:
           env: testing
spec:
        containers:
        - name: coo2
          image: ubuntu
          command: ["/bin/bash", "-c", "while true ; do echo Hello World ; sleep 5 ; done"]
        nodeSelector:
                hardware: t2-micro
          
