apiVersion: apps/v1
kind: ReplicaSet
metadata:
      name: myrs
spec:
     replicas: 2
     selector:
             matchExpressions:
                     - { key: myname , operator: In, values: [happy , HappySingh, hsingh]}
                     - { key: env , operator: NotIn , values: [producation]}
     template:
             metadata:
                  name:  testpod8
                  labels:
                      myname: happy
             spec:
                  containers:
                  - name: coo4
                    image: ubuntu
                    command: ["/bin/bash" , "-c", "while true ; do echo hey happy; sleep 6; done"]


